module_name: Authorize.net TestMe
compatible_versions: 1.0.0+
author: thirty bees
category: payment
localization:
  - US
  - CA
tags:
  - authorize
  - auth.net
  - authortize.net
  - payment module
description_short: The thirty bees Authorize.net module allows your site to accept payments using the Authorize.net payment gateway.
description: description.md
images:
  - image-1.png
  - image-2.png
license: MIT
